export * from "./Getstarted";
export * from "./About";
export * from "./Contact";
export * from "./Footer";
export * from "./Header";
export * from "./Howitworks";
export * from "./Startedmodal";
export * from "./Team";
export * from "./Categories";
